name: display the file content

on:
  push:
    branches: [ main ]

jobs:
  display-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read and display file content
        run: |
          FILE_PATH="hello.txt"  # Change this to your file path
          if [ -f "$FILE_PATH" ]; then
            echo "Contents of $FILE_PATH:"
            cat "$FILE_PATH"
          else
            echo "File $FILE_PATH not found"
            exit 1
          fi
